# apps/simple-go-app/base/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-go-app
  labels:
    app.kubernetes.io/name: simple-go-app
    app.kubernetes.io/component: backend
spec:
  ingressClassName: traefik
  rules:
    - host: simple-go-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-go-app
                port:
                  number: 80
